apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=us.gcr.io/prod-project-477306/myapp
    argocd-image-updater.argoproj.io/myapp.update-strategy: newest-build
    argocd-image-updater.argoproj.io/myapp.allow-tags: regexp:^\\d+$
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhizarkar7551/k8s-manifests-repo.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
